syntax = "proto3";

import "PortfolioAnalytic/Models/Requests/analytic_requests.proto";
import "PortfolioAnalytic/Models/Responses/analytic_responses.proto";


package cryptic.portfolio_analytic.rpc;


service PortfolioAnalyticService {
  rpc GetAssetAllocations(models.requests.CalculateWalletRequest) returns (models.responses.CalculateWalletResponse);
  rpc GetPortfolioVsTokenPoints(models.requests.GetPortfolioVsTokenPointsRequest)returns (models.responses.GetPortfolioCorrelationResponse);
  rpc GetPortfolioPnlPoints(models.requests.GetPortfolioPnlPointsRequest) returns (models.responses.GetPortfolioPnlPointsResponse);
}

service AnalyticTransactionService {
  rpc GetWalletTransactions(models.requests.GetWalletTransactionsRequest) returns (models.responses.GetWalletTransactionsResponse);
}