syntax = "proto3";

import "Base/v1/Models/Responses/task_response.proto";

package cryptic.portfolio_analytic.models.responses;

message WalletCoinResult {
  string symbol = 1;
  string image = 2;
  string dollarValue = 3;
  string percentage = 4;
}

message CalculateWalletResponse {
  repeated WalletCoinResult walletCoins = 1;
}


message TokenInfo {
  int32 tokenId = 1;
  string symbol = 2;
  string name = 3;
  string logoUri = 4;
  string lastPrice = 5;
}

message Transaction {
  int64 transactionId = 1;
  int32 walletId = 2;
  TokenInfo token = 3;
  string transactionHash = 4;
  string fromAddress = 5;
  string toAddress = 6;
  string amount = 7;
  int64 timestamp = 8;
  int32 transactionType = 9;
  string chain = 10;

  string fee = 11;
  int32 status = 12;
}

message GetWalletTransactionsResponse {
  repeated Transaction transactions = 1;
  int32 total = 2;
  int32 page = 3;
  int32 perPage = 4;
}

message PortfolioCorrelationPoint {
  int64 ts = 1;
  double portfolio_value = 2;
  double token_price = 3;
  double portfolio_change_pct = 4;
  double token_change_pct = 5;
}

message GetPortfolioCorrelationResponse {
  repeated PortfolioCorrelationPoint points = 1;
  base.v1.models.responses.TaskResponse result = 3;
}

message PnlPoint {
  int64 ts = 1;
  double profit = 2;
  double loss = 3;
}


message GetPortfolioPnlPointsResponse {
  repeated PnlPoint points = 1;
  base.v1.models.responses.TaskResponse result = 2;
}

message BalancePoint {
  int64 ts = 1;
  double balance = 2;
}

message GetPortfolioBalancePointsResponse {
  repeated BalancePoint points = 1;
  base.v1.models.responses.TaskResponse result = 2;
}
