syntax = "proto3";

import "BlockchainInteraction/Models/Responses/wallet_responses.proto";

package cryptic.portfolio_analytic.models.requests;

message CalculateWalletRequest {
  blockchain_interaction.models.responses.GetWalletCoinsResponse walletResponse = 1;
}

message WalletQuery {
  int32 walletId = 1;
  string walletAddress = 2;
}

message GetWalletTransactionsRequest {
  repeated WalletQuery wallets = 1;
  int32 page = 2;
  int32 perPage = 3;
  TransactionTypeFilter transactionType = 4;
  DateRange dateRange = 5;
  string search = 6;
}

message GetPortfolioVsTokenPointsRequest {
  repeated int32 wallet_ids = 1;
  string token_symbol = 2;
  int64 from_ts = 3;
  int64 to_ts = 4;
  int32 points_count = 5;
}

enum TransactionTypeFilter {
  ALL = 0;
  INCOMING = 1;
  OUTGOING = 2;
}

message DateRange {
  int64 from = 1;
  int64 to = 2;
}

message GetPortfolioPnlPointsRequest {
  repeated int32 wallet_ids = 1;
  int64 from_ts = 2;
  int64 to_ts = 3;
  int32 points_count = 4;
}

message GetPortfolioBalancePointsRequest {
  repeated int32 wallet_ids = 1;
  int64 from_ts = 2;
  int64 to_ts = 3;
  int32 points_count = 4;
}


