syntax = "proto3";

import "PortfolioConfiguration/Models/Responses/portfolio_responses.proto";
import "PortfolioAnalytic/Models/Requests/analytic_requests.proto";

package cryptic.portfolio_configuration.models.requests;

message CreatePortfolioRequest {
  string name = 1;
  int32 owner_id = 2;
  int64 created_at = 3;
}

message GetPortfolioCalculationRequest {
  int32 portfolioId = 1;
}

message GetPortfolioRequest {
  int32 id = 1;
  int32 owner_id = 2;
}

message GetPortfoliosByOwnerRequest {
  int32 owner_id = 1;
}

message UpdatePortfolioRequest {
  models.responses.Portfolio portfolio = 1;
}

message DeletePortfolioRequest {
  int32 id = 1;
  int32 owner_id = 2;
}

message ConnectWalletsRequest {
  int32 portfolio_id = 1;
  int32 owner_id = 2;
  repeated WalletConnectEntity wallets = 3;
}

message WalletConnectEntity{
  string name = 1;
  string caip_address = 2;
  string connector = 3;
  int32 connection_type = 4;
  string wallet_address = 5;
}

message GetPortfolioInfoRequest {
  int32 portfolio_id = 1;
  int32 owner_id = 2;
}

message PatchWalletVisibilityRequest {
  int32 portfolio_id = 1;
  int32 wallet_id = 2;
  int32 visibility = 3;
}

message GetWalletsByPortfolioIdRequest {
  int32 portfolio_id = 1;
}

message GetPortfolioTransactionsRequest {
  int32 portfolioId = 1;
  int32 page = 2;
  int32 perPage = 3;
  portfolio_analytic.models.requests.TransactionTypeFilter transactionType = 4;
  portfolio_analytic.models.requests.DateRange dateRange = 5;
  string search = 6;
}

message GetPortfolioCorrelationRequest {
  string token_symbol = 1;
  int32 portfolio_id = 2;
  int64 from_ts = 3;
  int64 to_ts = 4;
  int32 points_count = 5;
  int32 currency = 6;
}
