<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <RootNamespace>Cryptic_Domain</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Npgsql" Version="8.0.0" />
        <PackageReference Include="Grpc.AspNetCore" Version="2.57.0" />
        <PackageReference Include="MassTransit.RabbitMQ" Version="8.4.1" />
    </ItemGroup>

    <ItemGroup>
        <Protobuf Include="../../cryptic-domain/Cryptic Domain/Protos/Base/v1/Models/Responses/task_response.proto" GrpcServices="Server" AdditionalImportDirs="../../cryptic-domain/Cryptic Domain/Protos" />
        <Protobuf Include="../../cryptic-domain/Cryptic Domain/Protos/Base/v1/Models/Responses/error_model.proto" GrpcServices="Server" AdditionalImportDirs="../../cryptic-domain/Cryptic Domain/Protos" />
    </ItemGroup>

</Project>
