syntax = "proto3";

import "PortfolioConfiguration/Models/Requests/portfolio_requests.proto";
import "PortfolioConfiguration/Models/Responses/portfolio_responses.proto";
import "PortfolioAnalytic/Models/Responses/analytic_responses.proto";


package cryptic.portfolio_configuration.rpc;

service PortfolioService {
  rpc CreatePortfolio(models.requests.CreatePortfolioRequest) returns (models.responses.GetPortfolioResponse);
  rpc GetPortfolio(models.requests.GetPortfolioRequest) returns (models.responses.GetPortfolioResponse);
  rpc GetPortfoliosByOwner(models.requests.GetPortfoliosByOwnerRequest) returns (models.responses.GetPortfoliosByOwnerResponse);
  rpc UpdatePortfolio(models.requests.UpdatePortfolioRequest) returns (models.responses.GetPortfolioResponse);
  rpc DeletePortfolio(models.requests.DeletePortfolioRequest) returns (models.responses.DeletePortfolioResponse);
  rpc ConnectWallets(models.requests.ConnectWalletsRequest) returns (models.responses.ConnectWalletsResponse);
  rpc GetPortfolioInfo(cryptic.portfolio_configuration.models.requests.GetPortfolioInfoRequest) returns (cryptic.portfolio_configuration.models.responses.GetPortfolioInfoResponse);
  rpc PatchWalletVisibility (cryptic.portfolio_configuration.models.requests.PatchWalletVisibilityRequest) returns (cryptic.portfolio_configuration.models.responses.PatchWalletVisibilityResponse);
  rpc GetWalletsByPortfolioId (cryptic.portfolio_configuration.models.requests.GetWalletsByPortfolioIdRequest) returns (cryptic.portfolio_configuration.models.responses.GetWalletsByPortfolioIdResponse);
  rpc GetPortfolioCalculation(cryptic.portfolio_configuration.models.requests.GetPortfolioCalculationRequest)returns (cryptic.portfolio_configuration.models.responses.GetPortfolioCalculationResponse);
  rpc GetPortfolioTransactions(cryptic.portfolio_configuration.models.requests.GetPortfolioTransactionsRequest)returns (cryptic.portfolio_configuration.models.responses.GetPortfolioTransactionsResponse);
  rpc GetPortfolioWalletsInfo(cryptic.portfolio_configuration.models.requests.GetPortfolioInfoRequest) returns (cryptic.portfolio_configuration.models.responses.GetPortfolioWalletsInfoResponse);
  rpc GetPortfolioCorrelation(cryptic.portfolio_configuration.models.requests.GetPortfolioCorrelationRequest) returns (cryptic.portfolio_analytic.models.responses.GetPortfolioCorrelationResponse);
  rpc GetPortfolioPnlPoints(cryptic.portfolio_configuration.models.requests.GetPortfolioPnlPointsRequest) returns (cryptic.portfolio_analytic.models.responses.GetPortfolioPnlPointsResponse);
  
  
  
}

